// Minimal trace correlation: a trace id generated by the agent and propagated
// agent → registry → node via a header, so one logical operation is followable
// end to end in the (structured) logs. A production deployment swaps this for
// OpenTelemetry (W3C traceparent + spans exported to a collector) behind the
// same propagation point; the header name below is the seam.

import { randomBytes } from "node:crypto";
import type { IncomingMessage } from "node:http";

// Lowercase: Node normalizes request header names to lowercase.
export const TRACE_HEADER = "x-aleph-trace";

// A 128-bit hex trace id (same width as a W3C trace-id).
export function newTraceId(): string {
  return randomBytes(16).toString("hex");
}

// The inbound trace id if the caller propagated one, else a fresh id — so every
// request is correlatable even when the caller did not start a trace.
export function traceIdFrom(req: IncomingMessage): string {
  const h = req.headers[TRACE_HEADER];
  if (typeof h === "string" && /^[0-9a-f]{8,}$/i.test(h)) return h;
  return newTraceId();
}
